// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CoinInfosColumns holds the columns for the "coin_infos" table.
	CoinInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "name", Type: field.TypeString},
		{Name: "chain_type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "token_type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "official_contract", Type: field.TypeString, Unique: true},
		{Name: "private_contract", Type: field.TypeString, Unique: true},
		{Name: "remark", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "data", Type: field.TypeBytes, Nullable: true},
	}
	// CoinInfosTable holds the schema information for the "coin_infos" table.
	CoinInfosTable = &schema.Table{
		Name:       "coin_infos",
		Columns:    CoinInfosColumns,
		PrimaryKey: []*schema.Column{CoinInfosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CoinInfosTable,
	}
)

func init() {
}
