// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TokenInfosColumns holds the columns for the "token_infos" table.
	TokenInfosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "ent_id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "name", Type: field.TypeString},
		{Name: "chain_type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "token_type", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "unit", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "decimal", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "official_contract", Type: field.TypeString, Unique: true},
		{Name: "private_contract", Type: field.TypeString, Unique: true},
		{Name: "remark", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "data", Type: field.TypeBytes, Nullable: true},
	}
	// TokenInfosTable holds the schema information for the "token_infos" table.
	TokenInfosTable = &schema.Table{
		Name:       "token_infos",
		Columns:    TokenInfosColumns,
		PrimaryKey: []*schema.Column{TokenInfosColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tokeninfo_ent_id",
				Unique:  true,
				Columns: []*schema.Column{TokenInfosColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TokenInfosTable,
	}
)

func init() {
}
