// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/coininfo"
	"github.com/google/uuid"
)

// CoinInfoCreate is the builder for creating a CoinInfo entity.
type CoinInfoCreate struct {
	config
	mutation *CoinInfoMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (cic *CoinInfoCreate) SetCreatedAt(u uint32) *CoinInfoCreate {
	cic.mutation.SetCreatedAt(u)
	return cic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableCreatedAt(u *uint32) *CoinInfoCreate {
	if u != nil {
		cic.SetCreatedAt(*u)
	}
	return cic
}

// SetUpdatedAt sets the "updated_at" field.
func (cic *CoinInfoCreate) SetUpdatedAt(u uint32) *CoinInfoCreate {
	cic.mutation.SetUpdatedAt(u)
	return cic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableUpdatedAt(u *uint32) *CoinInfoCreate {
	if u != nil {
		cic.SetUpdatedAt(*u)
	}
	return cic
}

// SetDeletedAt sets the "deleted_at" field.
func (cic *CoinInfoCreate) SetDeletedAt(u uint32) *CoinInfoCreate {
	cic.mutation.SetDeletedAt(u)
	return cic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableDeletedAt(u *uint32) *CoinInfoCreate {
	if u != nil {
		cic.SetDeletedAt(*u)
	}
	return cic
}

// SetName sets the "name" field.
func (cic *CoinInfoCreate) SetName(s string) *CoinInfoCreate {
	cic.mutation.SetName(s)
	return cic
}

// SetChainType sets the "chain_type" field.
func (cic *CoinInfoCreate) SetChainType(s string) *CoinInfoCreate {
	cic.mutation.SetChainType(s)
	return cic
}

// SetNillableChainType sets the "chain_type" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableChainType(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetChainType(*s)
	}
	return cic
}

// SetTokenType sets the "token_type" field.
func (cic *CoinInfoCreate) SetTokenType(s string) *CoinInfoCreate {
	cic.mutation.SetTokenType(s)
	return cic
}

// SetNillableTokenType sets the "token_type" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableTokenType(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetTokenType(*s)
	}
	return cic
}

// SetOfficialContract sets the "official_contract" field.
func (cic *CoinInfoCreate) SetOfficialContract(s string) *CoinInfoCreate {
	cic.mutation.SetOfficialContract(s)
	return cic
}

// SetPrivateContract sets the "private_contract" field.
func (cic *CoinInfoCreate) SetPrivateContract(s string) *CoinInfoCreate {
	cic.mutation.SetPrivateContract(s)
	return cic
}

// SetRemark sets the "remark" field.
func (cic *CoinInfoCreate) SetRemark(s string) *CoinInfoCreate {
	cic.mutation.SetRemark(s)
	return cic
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableRemark(s *string) *CoinInfoCreate {
	if s != nil {
		cic.SetRemark(*s)
	}
	return cic
}

// SetData sets the "data" field.
func (cic *CoinInfoCreate) SetData(b []byte) *CoinInfoCreate {
	cic.mutation.SetData(b)
	return cic
}

// SetID sets the "id" field.
func (cic *CoinInfoCreate) SetID(u uuid.UUID) *CoinInfoCreate {
	cic.mutation.SetID(u)
	return cic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cic *CoinInfoCreate) SetNillableID(u *uuid.UUID) *CoinInfoCreate {
	if u != nil {
		cic.SetID(*u)
	}
	return cic
}

// Mutation returns the CoinInfoMutation object of the builder.
func (cic *CoinInfoCreate) Mutation() *CoinInfoMutation {
	return cic.mutation
}

// Save creates the CoinInfo in the database.
func (cic *CoinInfoCreate) Save(ctx context.Context) (*CoinInfo, error) {
	var (
		err  error
		node *CoinInfo
	)
	if err := cic.defaults(); err != nil {
		return nil, err
	}
	if len(cic.hooks) == 0 {
		if err = cic.check(); err != nil {
			return nil, err
		}
		node, err = cic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cic.check(); err != nil {
				return nil, err
			}
			cic.mutation = mutation
			if node, err = cic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cic.hooks) - 1; i >= 0; i-- {
			if cic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cic.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cic.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CoinInfo)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CoinInfoMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cic *CoinInfoCreate) SaveX(ctx context.Context) *CoinInfo {
	v, err := cic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cic *CoinInfoCreate) Exec(ctx context.Context) error {
	_, err := cic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cic *CoinInfoCreate) ExecX(ctx context.Context) {
	if err := cic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cic *CoinInfoCreate) defaults() error {
	if _, ok := cic.mutation.CreatedAt(); !ok {
		if coininfo.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized coininfo.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := coininfo.DefaultCreatedAt()
		cic.mutation.SetCreatedAt(v)
	}
	if _, ok := cic.mutation.UpdatedAt(); !ok {
		if coininfo.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coininfo.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coininfo.DefaultUpdatedAt()
		cic.mutation.SetUpdatedAt(v)
	}
	if _, ok := cic.mutation.DeletedAt(); !ok {
		if coininfo.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized coininfo.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := coininfo.DefaultDeletedAt()
		cic.mutation.SetDeletedAt(v)
	}
	if _, ok := cic.mutation.ChainType(); !ok {
		v := coininfo.DefaultChainType
		cic.mutation.SetChainType(v)
	}
	if _, ok := cic.mutation.TokenType(); !ok {
		v := coininfo.DefaultTokenType
		cic.mutation.SetTokenType(v)
	}
	if _, ok := cic.mutation.Remark(); !ok {
		v := coininfo.DefaultRemark
		cic.mutation.SetRemark(v)
	}
	if _, ok := cic.mutation.ID(); !ok {
		if coininfo.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized coininfo.DefaultID (forgotten import ent/runtime?)")
		}
		v := coininfo.DefaultID()
		cic.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cic *CoinInfoCreate) check() error {
	if _, ok := cic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CoinInfo.created_at"`)}
	}
	if _, ok := cic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CoinInfo.updated_at"`)}
	}
	if _, ok := cic.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "CoinInfo.deleted_at"`)}
	}
	if _, ok := cic.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CoinInfo.name"`)}
	}
	if _, ok := cic.mutation.OfficialContract(); !ok {
		return &ValidationError{Name: "official_contract", err: errors.New(`ent: missing required field "CoinInfo.official_contract"`)}
	}
	if _, ok := cic.mutation.PrivateContract(); !ok {
		return &ValidationError{Name: "private_contract", err: errors.New(`ent: missing required field "CoinInfo.private_contract"`)}
	}
	return nil
}

func (cic *CoinInfoCreate) sqlSave(ctx context.Context) (*CoinInfo, error) {
	_node, _spec := cic.createSpec()
	if err := sqlgraph.CreateNode(ctx, cic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (cic *CoinInfoCreate) createSpec() (*CoinInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &CoinInfo{config: cic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: coininfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coininfo.FieldID,
			},
		}
	)
	_spec.OnConflict = cic.conflict
	if id, ok := cic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cic.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coininfo.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cic.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coininfo.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := cic.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coininfo.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := cic.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldName,
		})
		_node.Name = value
	}
	if value, ok := cic.mutation.ChainType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldChainType,
		})
		_node.ChainType = value
	}
	if value, ok := cic.mutation.TokenType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldTokenType,
		})
		_node.TokenType = value
	}
	if value, ok := cic.mutation.OfficialContract(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldOfficialContract,
		})
		_node.OfficialContract = value
	}
	if value, ok := cic.mutation.PrivateContract(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldPrivateContract,
		})
		_node.PrivateContract = value
	}
	if value, ok := cic.mutation.Remark(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coininfo.FieldRemark,
		})
		_node.Remark = value
	}
	if value, ok := cic.mutation.Data(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: coininfo.FieldData,
		})
		_node.Data = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinInfo.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinInfoUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cic *CoinInfoCreate) OnConflict(opts ...sql.ConflictOption) *CoinInfoUpsertOne {
	cic.conflict = opts
	return &CoinInfoUpsertOne{
		create: cic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cic *CoinInfoCreate) OnConflictColumns(columns ...string) *CoinInfoUpsertOne {
	cic.conflict = append(cic.conflict, sql.ConflictColumns(columns...))
	return &CoinInfoUpsertOne{
		create: cic,
	}
}

type (
	// CoinInfoUpsertOne is the builder for "upsert"-ing
	//  one CoinInfo node.
	CoinInfoUpsertOne struct {
		create *CoinInfoCreate
	}

	// CoinInfoUpsert is the "OnConflict" setter.
	CoinInfoUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *CoinInfoUpsert) SetCreatedAt(v uint32) *CoinInfoUpsert {
	u.Set(coininfo.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateCreatedAt() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinInfoUpsert) AddCreatedAt(v uint32) *CoinInfoUpsert {
	u.Add(coininfo.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinInfoUpsert) SetUpdatedAt(v uint32) *CoinInfoUpsert {
	u.Set(coininfo.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateUpdatedAt() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinInfoUpsert) AddUpdatedAt(v uint32) *CoinInfoUpsert {
	u.Add(coininfo.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinInfoUpsert) SetDeletedAt(v uint32) *CoinInfoUpsert {
	u.Set(coininfo.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateDeletedAt() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinInfoUpsert) AddDeletedAt(v uint32) *CoinInfoUpsert {
	u.Add(coininfo.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *CoinInfoUpsert) SetName(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateName() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldName)
	return u
}

// SetChainType sets the "chain_type" field.
func (u *CoinInfoUpsert) SetChainType(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldChainType, v)
	return u
}

// UpdateChainType sets the "chain_type" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateChainType() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldChainType)
	return u
}

// ClearChainType clears the value of the "chain_type" field.
func (u *CoinInfoUpsert) ClearChainType() *CoinInfoUpsert {
	u.SetNull(coininfo.FieldChainType)
	return u
}

// SetTokenType sets the "token_type" field.
func (u *CoinInfoUpsert) SetTokenType(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldTokenType, v)
	return u
}

// UpdateTokenType sets the "token_type" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateTokenType() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldTokenType)
	return u
}

// ClearTokenType clears the value of the "token_type" field.
func (u *CoinInfoUpsert) ClearTokenType() *CoinInfoUpsert {
	u.SetNull(coininfo.FieldTokenType)
	return u
}

// SetOfficialContract sets the "official_contract" field.
func (u *CoinInfoUpsert) SetOfficialContract(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldOfficialContract, v)
	return u
}

// UpdateOfficialContract sets the "official_contract" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateOfficialContract() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldOfficialContract)
	return u
}

// SetPrivateContract sets the "private_contract" field.
func (u *CoinInfoUpsert) SetPrivateContract(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldPrivateContract, v)
	return u
}

// UpdatePrivateContract sets the "private_contract" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdatePrivateContract() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldPrivateContract)
	return u
}

// SetRemark sets the "remark" field.
func (u *CoinInfoUpsert) SetRemark(v string) *CoinInfoUpsert {
	u.Set(coininfo.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateRemark() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *CoinInfoUpsert) ClearRemark() *CoinInfoUpsert {
	u.SetNull(coininfo.FieldRemark)
	return u
}

// SetData sets the "data" field.
func (u *CoinInfoUpsert) SetData(v []byte) *CoinInfoUpsert {
	u.Set(coininfo.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *CoinInfoUpsert) UpdateData() *CoinInfoUpsert {
	u.SetExcluded(coininfo.FieldData)
	return u
}

// ClearData clears the value of the "data" field.
func (u *CoinInfoUpsert) ClearData() *CoinInfoUpsert {
	u.SetNull(coininfo.FieldData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coininfo.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinInfoUpsertOne) UpdateNewValues() *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coininfo.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.CoinInfo.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CoinInfoUpsertOne) Ignore() *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinInfoUpsertOne) DoNothing() *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinInfoCreate.OnConflict
// documentation for more info.
func (u *CoinInfoUpsertOne) Update(set func(*CoinInfoUpsert)) *CoinInfoUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinInfoUpsertOne) SetCreatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinInfoUpsertOne) AddCreatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateCreatedAt() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinInfoUpsertOne) SetUpdatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinInfoUpsertOne) AddUpdatedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateUpdatedAt() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinInfoUpsertOne) SetDeletedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinInfoUpsertOne) AddDeletedAt(v uint32) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateDeletedAt() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *CoinInfoUpsertOne) SetName(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateName() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateName()
	})
}

// SetChainType sets the "chain_type" field.
func (u *CoinInfoUpsertOne) SetChainType(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetChainType(v)
	})
}

// UpdateChainType sets the "chain_type" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateChainType() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateChainType()
	})
}

// ClearChainType clears the value of the "chain_type" field.
func (u *CoinInfoUpsertOne) ClearChainType() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearChainType()
	})
}

// SetTokenType sets the "token_type" field.
func (u *CoinInfoUpsertOne) SetTokenType(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetTokenType(v)
	})
}

// UpdateTokenType sets the "token_type" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateTokenType() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateTokenType()
	})
}

// ClearTokenType clears the value of the "token_type" field.
func (u *CoinInfoUpsertOne) ClearTokenType() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearTokenType()
	})
}

// SetOfficialContract sets the "official_contract" field.
func (u *CoinInfoUpsertOne) SetOfficialContract(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetOfficialContract(v)
	})
}

// UpdateOfficialContract sets the "official_contract" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateOfficialContract() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateOfficialContract()
	})
}

// SetPrivateContract sets the "private_contract" field.
func (u *CoinInfoUpsertOne) SetPrivateContract(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetPrivateContract(v)
	})
}

// UpdatePrivateContract sets the "private_contract" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdatePrivateContract() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdatePrivateContract()
	})
}

// SetRemark sets the "remark" field.
func (u *CoinInfoUpsertOne) SetRemark(v string) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateRemark() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *CoinInfoUpsertOne) ClearRemark() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearRemark()
	})
}

// SetData sets the "data" field.
func (u *CoinInfoUpsertOne) SetData(v []byte) *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *CoinInfoUpsertOne) UpdateData() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *CoinInfoUpsertOne) ClearData() *CoinInfoUpsertOne {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *CoinInfoUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinInfoCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinInfoUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoinInfoUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CoinInfoUpsertOne.ID is not supported by MySQL driver. Use CoinInfoUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoinInfoUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoinInfoCreateBulk is the builder for creating many CoinInfo entities in bulk.
type CoinInfoCreateBulk struct {
	config
	builders []*CoinInfoCreate
	conflict []sql.ConflictOption
}

// Save creates the CoinInfo entities in the database.
func (cicb *CoinInfoCreateBulk) Save(ctx context.Context) ([]*CoinInfo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cicb.builders))
	nodes := make([]*CoinInfo, len(cicb.builders))
	mutators := make([]Mutator, len(cicb.builders))
	for i := range cicb.builders {
		func(i int, root context.Context) {
			builder := cicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoinInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cicb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cicb *CoinInfoCreateBulk) SaveX(ctx context.Context) []*CoinInfo {
	v, err := cicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cicb *CoinInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := cicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cicb *CoinInfoCreateBulk) ExecX(ctx context.Context) {
	if err := cicb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinInfo.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinInfoUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cicb *CoinInfoCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoinInfoUpsertBulk {
	cicb.conflict = opts
	return &CoinInfoUpsertBulk{
		create: cicb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cicb *CoinInfoCreateBulk) OnConflictColumns(columns ...string) *CoinInfoUpsertBulk {
	cicb.conflict = append(cicb.conflict, sql.ConflictColumns(columns...))
	return &CoinInfoUpsertBulk{
		create: cicb,
	}
}

// CoinInfoUpsertBulk is the builder for "upsert"-ing
// a bulk of CoinInfo nodes.
type CoinInfoUpsertBulk struct {
	create *CoinInfoCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coininfo.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinInfoUpsertBulk) UpdateNewValues() *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coininfo.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoinInfo.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CoinInfoUpsertBulk) Ignore() *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinInfoUpsertBulk) DoNothing() *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinInfoCreateBulk.OnConflict
// documentation for more info.
func (u *CoinInfoUpsertBulk) Update(set func(*CoinInfoUpsert)) *CoinInfoUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinInfoUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinInfoUpsertBulk) SetCreatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinInfoUpsertBulk) AddCreatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateCreatedAt() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinInfoUpsertBulk) SetUpdatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinInfoUpsertBulk) AddUpdatedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateUpdatedAt() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinInfoUpsertBulk) SetDeletedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinInfoUpsertBulk) AddDeletedAt(v uint32) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateDeletedAt() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *CoinInfoUpsertBulk) SetName(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateName() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateName()
	})
}

// SetChainType sets the "chain_type" field.
func (u *CoinInfoUpsertBulk) SetChainType(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetChainType(v)
	})
}

// UpdateChainType sets the "chain_type" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateChainType() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateChainType()
	})
}

// ClearChainType clears the value of the "chain_type" field.
func (u *CoinInfoUpsertBulk) ClearChainType() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearChainType()
	})
}

// SetTokenType sets the "token_type" field.
func (u *CoinInfoUpsertBulk) SetTokenType(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetTokenType(v)
	})
}

// UpdateTokenType sets the "token_type" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateTokenType() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateTokenType()
	})
}

// ClearTokenType clears the value of the "token_type" field.
func (u *CoinInfoUpsertBulk) ClearTokenType() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearTokenType()
	})
}

// SetOfficialContract sets the "official_contract" field.
func (u *CoinInfoUpsertBulk) SetOfficialContract(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetOfficialContract(v)
	})
}

// UpdateOfficialContract sets the "official_contract" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateOfficialContract() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateOfficialContract()
	})
}

// SetPrivateContract sets the "private_contract" field.
func (u *CoinInfoUpsertBulk) SetPrivateContract(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetPrivateContract(v)
	})
}

// UpdatePrivateContract sets the "private_contract" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdatePrivateContract() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdatePrivateContract()
	})
}

// SetRemark sets the "remark" field.
func (u *CoinInfoUpsertBulk) SetRemark(v string) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateRemark() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *CoinInfoUpsertBulk) ClearRemark() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearRemark()
	})
}

// SetData sets the "data" field.
func (u *CoinInfoUpsertBulk) SetData(v []byte) *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *CoinInfoUpsertBulk) UpdateData() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.UpdateData()
	})
}

// ClearData clears the value of the "data" field.
func (u *CoinInfoUpsertBulk) ClearData() *CoinInfoUpsertBulk {
	return u.Update(func(s *CoinInfoUpsert) {
		s.ClearData()
	})
}

// Exec executes the query.
func (u *CoinInfoUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoinInfoCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinInfoCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinInfoUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
