// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/deployedcoin"
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// DeployedCoinQuery is the builder for querying DeployedCoin entities.
type DeployedCoinQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.DeployedCoin
	modifiers  []func(s *sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeployedCoinQuery builder.
func (dcq *DeployedCoinQuery) Where(ps ...predicate.DeployedCoin) *DeployedCoinQuery {
	dcq.predicates = append(dcq.predicates, ps...)
	return dcq
}

// Limit adds a limit step to the query.
func (dcq *DeployedCoinQuery) Limit(limit int) *DeployedCoinQuery {
	dcq.limit = &limit
	return dcq
}

// Offset adds an offset step to the query.
func (dcq *DeployedCoinQuery) Offset(offset int) *DeployedCoinQuery {
	dcq.offset = &offset
	return dcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dcq *DeployedCoinQuery) Unique(unique bool) *DeployedCoinQuery {
	dcq.unique = &unique
	return dcq
}

// Order adds an order step to the query.
func (dcq *DeployedCoinQuery) Order(o ...OrderFunc) *DeployedCoinQuery {
	dcq.order = append(dcq.order, o...)
	return dcq
}

// First returns the first DeployedCoin entity from the query.
// Returns a *NotFoundError when no DeployedCoin was found.
func (dcq *DeployedCoinQuery) First(ctx context.Context) (*DeployedCoin, error) {
	nodes, err := dcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deployedcoin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dcq *DeployedCoinQuery) FirstX(ctx context.Context) *DeployedCoin {
	node, err := dcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeployedCoin ID from the query.
// Returns a *NotFoundError when no DeployedCoin ID was found.
func (dcq *DeployedCoinQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deployedcoin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dcq *DeployedCoinQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeployedCoin entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeployedCoin entity is found.
// Returns a *NotFoundError when no DeployedCoin entities are found.
func (dcq *DeployedCoinQuery) Only(ctx context.Context) (*DeployedCoin, error) {
	nodes, err := dcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deployedcoin.Label}
	default:
		return nil, &NotSingularError{deployedcoin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dcq *DeployedCoinQuery) OnlyX(ctx context.Context) *DeployedCoin {
	node, err := dcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeployedCoin ID in the query.
// Returns a *NotSingularError when more than one DeployedCoin ID is found.
// Returns a *NotFoundError when no entities are found.
func (dcq *DeployedCoinQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = &NotSingularError{deployedcoin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dcq *DeployedCoinQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeployedCoins.
func (dcq *DeployedCoinQuery) All(ctx context.Context) ([]*DeployedCoin, error) {
	if err := dcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return dcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (dcq *DeployedCoinQuery) AllX(ctx context.Context) []*DeployedCoin {
	nodes, err := dcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeployedCoin IDs.
func (dcq *DeployedCoinQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := dcq.Select(deployedcoin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dcq *DeployedCoinQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dcq *DeployedCoinQuery) Count(ctx context.Context) (int, error) {
	if err := dcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return dcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (dcq *DeployedCoinQuery) CountX(ctx context.Context) int {
	count, err := dcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dcq *DeployedCoinQuery) Exist(ctx context.Context) (bool, error) {
	if err := dcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return dcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (dcq *DeployedCoinQuery) ExistX(ctx context.Context) bool {
	exist, err := dcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeployedCoinQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dcq *DeployedCoinQuery) Clone() *DeployedCoinQuery {
	if dcq == nil {
		return nil
	}
	return &DeployedCoinQuery{
		config:     dcq.config,
		limit:      dcq.limit,
		offset:     dcq.offset,
		order:      append([]OrderFunc{}, dcq.order...),
		predicates: append([]predicate.DeployedCoin{}, dcq.predicates...),
		// clone intermediate query.
		sql:    dcq.sql.Clone(),
		path:   dcq.path,
		unique: dcq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeployedCoin.Query().
//		GroupBy(deployedcoin.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (dcq *DeployedCoinQuery) GroupBy(field string, fields ...string) *DeployedCoinGroupBy {
	group := &DeployedCoinGroupBy{config: dcq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := dcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return dcq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.DeployedCoin.Query().
//		Select(deployedcoin.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (dcq *DeployedCoinQuery) Select(fields ...string) *DeployedCoinSelect {
	dcq.fields = append(dcq.fields, fields...)
	return &DeployedCoinSelect{DeployedCoinQuery: dcq}
}

func (dcq *DeployedCoinQuery) prepareQuery(ctx context.Context) error {
	for _, f := range dcq.fields {
		if !deployedcoin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dcq.path != nil {
		prev, err := dcq.path(ctx)
		if err != nil {
			return err
		}
		dcq.sql = prev
	}
	if deployedcoin.Policy == nil {
		return errors.New("ent: uninitialized deployedcoin.Policy (forgotten import ent/runtime?)")
	}
	if err := deployedcoin.Policy.EvalQuery(ctx, dcq); err != nil {
		return err
	}
	return nil
}

func (dcq *DeployedCoinQuery) sqlAll(ctx context.Context) ([]*DeployedCoin, error) {
	var (
		nodes = []*DeployedCoin{}
		_spec = dcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &DeployedCoin{config: dcq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if len(dcq.modifiers) > 0 {
		_spec.Modifiers = dcq.modifiers
	}
	if err := sqlgraph.QueryNodes(ctx, dcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (dcq *DeployedCoinQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dcq.querySpec()
	if len(dcq.modifiers) > 0 {
		_spec.Modifiers = dcq.modifiers
	}
	_spec.Node.Columns = dcq.fields
	if len(dcq.fields) > 0 {
		_spec.Unique = dcq.unique != nil && *dcq.unique
	}
	return sqlgraph.CountNodes(ctx, dcq.driver, _spec)
}

func (dcq *DeployedCoinQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := dcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (dcq *DeployedCoinQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   deployedcoin.Table,
			Columns: deployedcoin.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: deployedcoin.FieldID,
			},
		},
		From:   dcq.sql,
		Unique: true,
	}
	if unique := dcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := dcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deployedcoin.FieldID)
		for i := range fields {
			if fields[i] != deployedcoin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dcq *DeployedCoinQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dcq.driver.Dialect())
	t1 := builder.Table(deployedcoin.Table)
	columns := dcq.fields
	if len(columns) == 0 {
		columns = deployedcoin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dcq.sql != nil {
		selector = dcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dcq.unique != nil && *dcq.unique {
		selector.Distinct()
	}
	for _, m := range dcq.modifiers {
		m(selector)
	}
	for _, p := range dcq.predicates {
		p(selector)
	}
	for _, p := range dcq.order {
		p(selector)
	}
	if offset := dcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (dcq *DeployedCoinQuery) ForUpdate(opts ...sql.LockOption) *DeployedCoinQuery {
	if dcq.driver.Dialect() == dialect.Postgres {
		dcq.Unique(false)
	}
	dcq.modifiers = append(dcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return dcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (dcq *DeployedCoinQuery) ForShare(opts ...sql.LockOption) *DeployedCoinQuery {
	if dcq.driver.Dialect() == dialect.Postgres {
		dcq.Unique(false)
	}
	dcq.modifiers = append(dcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return dcq
}

// DeployedCoinGroupBy is the group-by builder for DeployedCoin entities.
type DeployedCoinGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dcgb *DeployedCoinGroupBy) Aggregate(fns ...AggregateFunc) *DeployedCoinGroupBy {
	dcgb.fns = append(dcgb.fns, fns...)
	return dcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (dcgb *DeployedCoinGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := dcgb.path(ctx)
	if err != nil {
		return err
	}
	dcgb.sql = query
	return dcgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := dcgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(dcgb.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := dcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) StringsX(ctx context.Context) []string {
	v, err := dcgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dcgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) StringX(ctx context.Context) string {
	v, err := dcgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(dcgb.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := dcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) IntsX(ctx context.Context) []int {
	v, err := dcgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dcgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) IntX(ctx context.Context) int {
	v, err := dcgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(dcgb.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := dcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := dcgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dcgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) Float64X(ctx context.Context) float64 {
	v, err := dcgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(dcgb.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := dcgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := dcgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (dcgb *DeployedCoinGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dcgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dcgb *DeployedCoinGroupBy) BoolX(ctx context.Context) bool {
	v, err := dcgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dcgb *DeployedCoinGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range dcgb.fields {
		if !deployedcoin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := dcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (dcgb *DeployedCoinGroupBy) sqlQuery() *sql.Selector {
	selector := dcgb.sql.Select()
	aggregation := make([]string, 0, len(dcgb.fns))
	for _, fn := range dcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(dcgb.fields)+len(dcgb.fns))
		for _, f := range dcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(dcgb.fields...)...)
}

// DeployedCoinSelect is the builder for selecting fields of DeployedCoin entities.
type DeployedCoinSelect struct {
	*DeployedCoinQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (dcs *DeployedCoinSelect) Scan(ctx context.Context, v interface{}) error {
	if err := dcs.prepareQuery(ctx); err != nil {
		return err
	}
	dcs.sql = dcs.DeployedCoinQuery.sqlQuery(ctx)
	return dcs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (dcs *DeployedCoinSelect) ScanX(ctx context.Context, v interface{}) {
	if err := dcs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) Strings(ctx context.Context) ([]string, error) {
	if len(dcs.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := dcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (dcs *DeployedCoinSelect) StringsX(ctx context.Context) []string {
	v, err := dcs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = dcs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (dcs *DeployedCoinSelect) StringX(ctx context.Context) string {
	v, err := dcs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) Ints(ctx context.Context) ([]int, error) {
	if len(dcs.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := dcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (dcs *DeployedCoinSelect) IntsX(ctx context.Context) []int {
	v, err := dcs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = dcs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (dcs *DeployedCoinSelect) IntX(ctx context.Context) int {
	v, err := dcs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(dcs.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := dcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (dcs *DeployedCoinSelect) Float64sX(ctx context.Context) []float64 {
	v, err := dcs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = dcs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (dcs *DeployedCoinSelect) Float64X(ctx context.Context) float64 {
	v, err := dcs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(dcs.fields) > 1 {
		return nil, errors.New("ent: DeployedCoinSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := dcs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (dcs *DeployedCoinSelect) BoolsX(ctx context.Context) []bool {
	v, err := dcs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (dcs *DeployedCoinSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = dcs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{deployedcoin.Label}
	default:
		err = fmt.Errorf("ent: DeployedCoinSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (dcs *DeployedCoinSelect) BoolX(ctx context.Context) bool {
	v, err := dcs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dcs *DeployedCoinSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := dcs.sql.Query()
	if err := dcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
