// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/coininfo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   coininfo.Table,
			Columns: coininfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: coininfo.FieldID,
			},
		},
		Type: "CoinInfo",
		Fields: map[string]*sqlgraph.FieldSpec{
			coininfo.FieldCreatedAt:        {Type: field.TypeUint32, Column: coininfo.FieldCreatedAt},
			coininfo.FieldUpdatedAt:        {Type: field.TypeUint32, Column: coininfo.FieldUpdatedAt},
			coininfo.FieldDeletedAt:        {Type: field.TypeUint32, Column: coininfo.FieldDeletedAt},
			coininfo.FieldName:             {Type: field.TypeString, Column: coininfo.FieldName},
			coininfo.FieldChainType:        {Type: field.TypeString, Column: coininfo.FieldChainType},
			coininfo.FieldTokenType:        {Type: field.TypeString, Column: coininfo.FieldTokenType},
			coininfo.FieldOfficialContract: {Type: field.TypeString, Column: coininfo.FieldOfficialContract},
			coininfo.FieldPrivateContract:  {Type: field.TypeString, Column: coininfo.FieldPrivateContract},
			coininfo.FieldRemark:           {Type: field.TypeString, Column: coininfo.FieldRemark},
			coininfo.FieldData:             {Type: field.TypeBytes, Column: coininfo.FieldData},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (ciq *CoinInfoQuery) addPredicate(pred func(s *sql.Selector)) {
	ciq.predicates = append(ciq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the CoinInfoQuery builder.
func (ciq *CoinInfoQuery) Filter() *CoinInfoFilter {
	return &CoinInfoFilter{config: ciq.config, predicateAdder: ciq}
}

// addPredicate implements the predicateAdder interface.
func (m *CoinInfoMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the CoinInfoMutation builder.
func (m *CoinInfoMutation) Filter() *CoinInfoFilter {
	return &CoinInfoFilter{config: m.config, predicateAdder: m}
}

// CoinInfoFilter provides a generic filtering capability at runtime for CoinInfoQuery.
type CoinInfoFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *CoinInfoFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *CoinInfoFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(coininfo.FieldID))
}

// WhereCreatedAt applies the entql uint32 predicate on the created_at field.
func (f *CoinInfoFilter) WhereCreatedAt(p entql.Uint32P) {
	f.Where(p.Field(coininfo.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql uint32 predicate on the updated_at field.
func (f *CoinInfoFilter) WhereUpdatedAt(p entql.Uint32P) {
	f.Where(p.Field(coininfo.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql uint32 predicate on the deleted_at field.
func (f *CoinInfoFilter) WhereDeletedAt(p entql.Uint32P) {
	f.Where(p.Field(coininfo.FieldDeletedAt))
}

// WhereName applies the entql string predicate on the name field.
func (f *CoinInfoFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(coininfo.FieldName))
}

// WhereChainType applies the entql string predicate on the chain_type field.
func (f *CoinInfoFilter) WhereChainType(p entql.StringP) {
	f.Where(p.Field(coininfo.FieldChainType))
}

// WhereTokenType applies the entql string predicate on the token_type field.
func (f *CoinInfoFilter) WhereTokenType(p entql.StringP) {
	f.Where(p.Field(coininfo.FieldTokenType))
}

// WhereOfficialContract applies the entql string predicate on the official_contract field.
func (f *CoinInfoFilter) WhereOfficialContract(p entql.StringP) {
	f.Where(p.Field(coininfo.FieldOfficialContract))
}

// WherePrivateContract applies the entql string predicate on the private_contract field.
func (f *CoinInfoFilter) WherePrivateContract(p entql.StringP) {
	f.Where(p.Field(coininfo.FieldPrivateContract))
}

// WhereRemark applies the entql string predicate on the remark field.
func (f *CoinInfoFilter) WhereRemark(p entql.StringP) {
	f.Where(p.Field(coininfo.FieldRemark))
}

// WhereData applies the entql []byte predicate on the data field.
func (f *CoinInfoFilter) WhereData(p entql.BytesP) {
	f.Where(p.Field(coininfo.FieldData))
}
