// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/tokeninfo"
)

// TokenInfoQuery is the builder for querying TokenInfo entities.
type TokenInfoQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TokenInfo
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TokenInfoQuery builder.
func (tiq *TokenInfoQuery) Where(ps ...predicate.TokenInfo) *TokenInfoQuery {
	tiq.predicates = append(tiq.predicates, ps...)
	return tiq
}

// Limit adds a limit step to the query.
func (tiq *TokenInfoQuery) Limit(limit int) *TokenInfoQuery {
	tiq.limit = &limit
	return tiq
}

// Offset adds an offset step to the query.
func (tiq *TokenInfoQuery) Offset(offset int) *TokenInfoQuery {
	tiq.offset = &offset
	return tiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tiq *TokenInfoQuery) Unique(unique bool) *TokenInfoQuery {
	tiq.unique = &unique
	return tiq
}

// Order adds an order step to the query.
func (tiq *TokenInfoQuery) Order(o ...OrderFunc) *TokenInfoQuery {
	tiq.order = append(tiq.order, o...)
	return tiq
}

// First returns the first TokenInfo entity from the query.
// Returns a *NotFoundError when no TokenInfo was found.
func (tiq *TokenInfoQuery) First(ctx context.Context) (*TokenInfo, error) {
	nodes, err := tiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tokeninfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tiq *TokenInfoQuery) FirstX(ctx context.Context) *TokenInfo {
	node, err := tiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TokenInfo ID from the query.
// Returns a *NotFoundError when no TokenInfo ID was found.
func (tiq *TokenInfoQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = tiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tokeninfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tiq *TokenInfoQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := tiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TokenInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TokenInfo entity is found.
// Returns a *NotFoundError when no TokenInfo entities are found.
func (tiq *TokenInfoQuery) Only(ctx context.Context) (*TokenInfo, error) {
	nodes, err := tiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tokeninfo.Label}
	default:
		return nil, &NotSingularError{tokeninfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tiq *TokenInfoQuery) OnlyX(ctx context.Context) *TokenInfo {
	node, err := tiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TokenInfo ID in the query.
// Returns a *NotSingularError when more than one TokenInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (tiq *TokenInfoQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = tiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tokeninfo.Label}
	default:
		err = &NotSingularError{tokeninfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tiq *TokenInfoQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := tiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TokenInfos.
func (tiq *TokenInfoQuery) All(ctx context.Context) ([]*TokenInfo, error) {
	if err := tiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tiq *TokenInfoQuery) AllX(ctx context.Context) []*TokenInfo {
	nodes, err := tiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TokenInfo IDs.
func (tiq *TokenInfoQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := tiq.Select(tokeninfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tiq *TokenInfoQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := tiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tiq *TokenInfoQuery) Count(ctx context.Context) (int, error) {
	if err := tiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tiq *TokenInfoQuery) CountX(ctx context.Context) int {
	count, err := tiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tiq *TokenInfoQuery) Exist(ctx context.Context) (bool, error) {
	if err := tiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tiq *TokenInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := tiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TokenInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tiq *TokenInfoQuery) Clone() *TokenInfoQuery {
	if tiq == nil {
		return nil
	}
	return &TokenInfoQuery{
		config:     tiq.config,
		limit:      tiq.limit,
		offset:     tiq.offset,
		order:      append([]OrderFunc{}, tiq.order...),
		predicates: append([]predicate.TokenInfo{}, tiq.predicates...),
		// clone intermediate query.
		sql:    tiq.sql.Clone(),
		path:   tiq.path,
		unique: tiq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EntID uuid.UUID `json:"ent_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TokenInfo.Query().
//		GroupBy(tokeninfo.FieldEntID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tiq *TokenInfoQuery) GroupBy(field string, fields ...string) *TokenInfoGroupBy {
	grbuild := &TokenInfoGroupBy{config: tiq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tiq.sqlQuery(ctx), nil
	}
	grbuild.label = tokeninfo.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EntID uuid.UUID `json:"ent_id,omitempty"`
//	}
//
//	client.TokenInfo.Query().
//		Select(tokeninfo.FieldEntID).
//		Scan(ctx, &v)
func (tiq *TokenInfoQuery) Select(fields ...string) *TokenInfoSelect {
	tiq.fields = append(tiq.fields, fields...)
	selbuild := &TokenInfoSelect{TokenInfoQuery: tiq}
	selbuild.label = tokeninfo.Label
	selbuild.flds, selbuild.scan = &tiq.fields, selbuild.Scan
	return selbuild
}

func (tiq *TokenInfoQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tiq.fields {
		if !tokeninfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tiq.path != nil {
		prev, err := tiq.path(ctx)
		if err != nil {
			return err
		}
		tiq.sql = prev
	}
	if tokeninfo.Policy == nil {
		return errors.New("ent: uninitialized tokeninfo.Policy (forgotten import ent/runtime?)")
	}
	if err := tokeninfo.Policy.EvalQuery(ctx, tiq); err != nil {
		return err
	}
	return nil
}

func (tiq *TokenInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TokenInfo, error) {
	var (
		nodes = []*TokenInfo{}
		_spec = tiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*TokenInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &TokenInfo{config: tiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(tiq.modifiers) > 0 {
		_spec.Modifiers = tiq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tiq *TokenInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tiq.querySpec()
	if len(tiq.modifiers) > 0 {
		_spec.Modifiers = tiq.modifiers
	}
	_spec.Node.Columns = tiq.fields
	if len(tiq.fields) > 0 {
		_spec.Unique = tiq.unique != nil && *tiq.unique
	}
	return sqlgraph.CountNodes(ctx, tiq.driver, _spec)
}

func (tiq *TokenInfoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tiq *TokenInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tokeninfo.Table,
			Columns: tokeninfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: tokeninfo.FieldID,
			},
		},
		From:   tiq.sql,
		Unique: true,
	}
	if unique := tiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokeninfo.FieldID)
		for i := range fields {
			if fields[i] != tokeninfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tiq *TokenInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tiq.driver.Dialect())
	t1 := builder.Table(tokeninfo.Table)
	columns := tiq.fields
	if len(columns) == 0 {
		columns = tokeninfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tiq.sql != nil {
		selector = tiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tiq.unique != nil && *tiq.unique {
		selector.Distinct()
	}
	for _, m := range tiq.modifiers {
		m(selector)
	}
	for _, p := range tiq.predicates {
		p(selector)
	}
	for _, p := range tiq.order {
		p(selector)
	}
	if offset := tiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tiq *TokenInfoQuery) Modify(modifiers ...func(s *sql.Selector)) *TokenInfoSelect {
	tiq.modifiers = append(tiq.modifiers, modifiers...)
	return tiq.Select()
}

// TokenInfoGroupBy is the group-by builder for TokenInfo entities.
type TokenInfoGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tigb *TokenInfoGroupBy) Aggregate(fns ...AggregateFunc) *TokenInfoGroupBy {
	tigb.fns = append(tigb.fns, fns...)
	return tigb
}

// Scan applies the group-by query and scans the result into the given value.
func (tigb *TokenInfoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tigb.path(ctx)
	if err != nil {
		return err
	}
	tigb.sql = query
	return tigb.sqlScan(ctx, v)
}

func (tigb *TokenInfoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tigb.fields {
		if !tokeninfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tigb *TokenInfoGroupBy) sqlQuery() *sql.Selector {
	selector := tigb.sql.Select()
	aggregation := make([]string, 0, len(tigb.fns))
	for _, fn := range tigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tigb.fields)+len(tigb.fns))
		for _, f := range tigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tigb.fields...)...)
}

// TokenInfoSelect is the builder for selecting fields of TokenInfo entities.
type TokenInfoSelect struct {
	*TokenInfoQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tis *TokenInfoSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tis.prepareQuery(ctx); err != nil {
		return err
	}
	tis.sql = tis.TokenInfoQuery.sqlQuery(ctx)
	return tis.sqlScan(ctx, v)
}

func (tis *TokenInfoSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tis.sql.Query()
	if err := tis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tis *TokenInfoSelect) Modify(modifiers ...func(s *sql.Selector)) *TokenInfoSelect {
	tis.modifiers = append(tis.modifiers, modifiers...)
	return tis
}
