// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/build-chain/pkg/db/ent/tokeninfo"
)

// TokenInfoDelete is the builder for deleting a TokenInfo entity.
type TokenInfoDelete struct {
	config
	hooks    []Hook
	mutation *TokenInfoMutation
}

// Where appends a list predicates to the TokenInfoDelete builder.
func (tid *TokenInfoDelete) Where(ps ...predicate.TokenInfo) *TokenInfoDelete {
	tid.mutation.Where(ps...)
	return tid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tid *TokenInfoDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tid.hooks) == 0 {
		affected, err = tid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TokenInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tid.mutation = mutation
			affected, err = tid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tid.hooks) - 1; i >= 0; i-- {
			if tid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tid *TokenInfoDelete) ExecX(ctx context.Context) int {
	n, err := tid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tid *TokenInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: tokeninfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: tokeninfo.FieldID,
			},
		},
	}
	if ps := tid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// TokenInfoDeleteOne is the builder for deleting a single TokenInfo entity.
type TokenInfoDeleteOne struct {
	tid *TokenInfoDelete
}

// Exec executes the deletion query.
func (tido *TokenInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := tido.tid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tokeninfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tido *TokenInfoDeleteOne) ExecX(ctx context.Context) {
	tido.tid.ExecX(ctx)
}
