apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-chain
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: build-chain
  template:
    metadata:
      labels:
        app: build-chain
    spec:
      containers:
        - name: build-chain
          image: uhub.service.ucloud.cn/entropypool/build-chain:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/BuildChain
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: build-chain-config
            items:
              - key: service-conf
                path: BuildChain.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: build-chain
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50490
      targetPort: 50490
    - name: grpc
      port: 50491
      targetPort: 50491
    - name: healthz
      port: 50493
      targetPort: 50493
    - name: prometheus
      port: 50492
      targetPort: 50492
  selector:
    app: build-chain
